[doc('Runs the tests without generating coverage file')]
test-nocov:
    pytest /workspaces/algo2024/python

[doc('Runs the tests and generates coverage file')]
test:
    poetry run pytest --cov-report lcov --cov
